package com.distpaint;

import java.awt.Color;
import javax.swing.JColorChooser;

public class DialogoDibujo extends javax.swing.JFrame {

    private final LienzoCompartido lienzo;

    public DialogoDibujo(LienzoCompartido lienzo) {
        initComponents();
        this.lienzo = lienzo;

        this.previstaColorRelleno.setBackground(lienzo.getColorRelleno());
        this.previstaColorBorde.setBackground(lienzo.getColorBorde());
        this.sliderMagnitudBorde.setValue(lienzo.getMagnitudBorde());
        this.checkboxUsarRelleno.setSelected(lienzo.isRellenar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaGrueso = new javax.swing.JLabel();
        botonColorRelleno = new javax.swing.JButton();
        botonColorBorde = new javax.swing.JButton();
        previstaColorRelleno = new javax.swing.JPanel();
        previstaColorBorde = new javax.swing.JPanel();
        checkboxUsarRelleno = new javax.swing.JCheckBox();
        sliderMagnitudBorde = new javax.swing.JSlider();

        setTitle("Propiedades");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        etiquetaGrueso.setText("Grueso borde:");

        botonColorRelleno.setText("Color relleno");
        botonColorRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorRellenoActionPerformed(evt);
            }
        });

        botonColorBorde.setText("Color borde");
        botonColorBorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorBordeActionPerformed(evt);
            }
        });

        previstaColorRelleno.setBackground(new java.awt.Color(0, 0, 0));
        previstaColorRelleno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout previstaColorRellenoLayout = new javax.swing.GroupLayout(previstaColorRelleno);
        previstaColorRelleno.setLayout(previstaColorRellenoLayout);
        previstaColorRellenoLayout.setHorizontalGroup(
            previstaColorRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        previstaColorRellenoLayout.setVerticalGroup(
            previstaColorRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        previstaColorBorde.setBackground(new java.awt.Color(255, 255, 255));
        previstaColorBorde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout previstaColorBordeLayout = new javax.swing.GroupLayout(previstaColorBorde);
        previstaColorBorde.setLayout(previstaColorBordeLayout);
        previstaColorBordeLayout.setHorizontalGroup(
            previstaColorBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        previstaColorBordeLayout.setVerticalGroup(
            previstaColorBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        checkboxUsarRelleno.setSelected(true);
        checkboxUsarRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxUsarRellenoActionPerformed(evt);
            }
        });

        sliderMagnitudBorde.setValue(10);
        sliderMagnitudBorde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMagnitudBordeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkboxUsarRelleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonColorBorde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonColorRelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(previstaColorRelleno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previstaColorBorde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaGrueso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderMagnitudBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(previstaColorRelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonColorRelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkboxUsarRelleno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonColorBorde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previstaColorBorde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaGrueso)
                    .addComponent(sliderMagnitudBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderMagnitudBordeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMagnitudBordeStateChanged
        this.lienzo.setMagnitudBorde(this.sliderMagnitudBorde.getValue());
    }//GEN-LAST:event_sliderMagnitudBordeStateChanged

    private void checkboxUsarRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxUsarRellenoActionPerformed
        this.lienzo.setRellenar(this.checkboxUsarRelleno.isSelected());
    }//GEN-LAST:event_checkboxUsarRellenoActionPerformed

    private void botonColorRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorRellenoActionPerformed
        Color relleno = JColorChooser.showDialog(this, "Color de relleno", this.lienzo.getColorRelleno());
        if (relleno != null) {
            this.previstaColorRelleno.setBackground(relleno);
            this.lienzo.setColorRelleno(relleno);
        }
    }//GEN-LAST:event_botonColorRellenoActionPerformed

    private void botonColorBordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorBordeActionPerformed
        Color borde = JColorChooser.showDialog(this, "Color de borde", this.lienzo.getColorBorde());
        if (borde != null) {
            this.previstaColorBorde.setBackground(borde);
            this.lienzo.setColorBorde(borde);
        }
    }//GEN-LAST:event_botonColorBordeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonColorBorde;
    private javax.swing.JButton botonColorRelleno;
    private javax.swing.JCheckBox checkboxUsarRelleno;
    private javax.swing.JLabel etiquetaGrueso;
    private javax.swing.JPanel previstaColorBorde;
    private javax.swing.JPanel previstaColorRelleno;
    private javax.swing.JSlider sliderMagnitudBorde;
    // End of variables declaration//GEN-END:variables
}
